# Generated by Django 4.2.4 on 2026-02-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='version',
        ),
    ]
