# Generated by Django 4.2.4 on 2026-02-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_screen_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='phone_type',
        ),
        migrations.AddField(
            model_name='screen',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
